apiVersion: v1
kind: Service
metadata:
  name: redis-master-dav
  labels:
    app: redis-dav
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-dav
    role: master
    tier: backend
